services:
  php:
    build: ./php
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0 
    environment:
      MYSQL_ROOT_PASSWORD: TK12345
      MYSQL_DATABASE: bira_website
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
